setup.template.name: "filebeat-"
setup.template.pattern: "filebeat-*"
setup.dashboards.enabled: true
setup.kibana.host: 'kibana:5601'
setup.kibana.protocol: "http"
setup.kibana.path: ''
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/filebeat/*.log

output.logstash:
  hosts: ['logstash:5000']
  tls:
    insecure: true

