setup.template.name: "filebeat-"
setup.template.pattern: "filebeat-*"
setup.dashboards.enabled: true
setup.kibana.host: 'kibana:5601'
setup.kibana.protocol: "http"
setup.kibana.path: ''

filebeat.inputs:
- type: log
  enabled: true
  paths:
   - '/var/lib/docker/containers/*/*.log'
  json.message_key: log
  json.keys_under_root: true
  processors:
  - add_docker_metadata: ~

autodiscover.providers:
  - type: docker
    templates:
      - condition.contains:
          docker.container.image: nginx
        config:
          - type: log
            paths:
              - "/mnt/logs/${data.docker.container.id}/*.log"

output.logstash:
  enabled: true
  hosts: ['127.0.0.1:5000']
  tls:
    insecure: true

