setup.template.name: "filebeat-"
setup.template.pattern: "filebeat-*"
setup.dashboards.enabled: true
setup.kibana.host: 'kibana:5601'
setup.kibana.protocol: "http"
setup.kibana.path: ''
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/filebeat/*.log

filebeat.prospectors:
- type: log
  paths:
   - '/var/lib/docker/containers/*/*.log'
  json.message_key: log
  json.keys_under_root: true
  processors:
  - add_docker_metadata: ~

output.logstash:
  enabled: true
  hosts: ['logstash:5000']
  tls:
    insecure: true

