setup.dashboards.enabled: false
setup.kibana.ssl.enabled: false
setup.template.name: "filebeat-"
setup.template.pattern: "filebeat-*"

filebeat.inputs:
- type: log
  enabled: true
  paths:
   - '/var/lib/docker/containers/*/*.log'
  json.message_key: log
  json.keys_under_root: true
  processors:
  - add_docker_metadata: ~

output.logstash:
  enabled: true
  hosts: ['logstash:5000']
  index: "weblogs-%{+YYYY.MM.dd}"
  tls:
    insecure: true