filebeat.prospectors:
- type: log
  paths:
    - /usr/share/filebeat/logs/*.log

setup.template.name: "filebeat-"
setup.template.pattern: "filebeat-*"
setup.dashboards.enabled: true

output.logstash:
  hosts: ["http://localhost:5000"]