filebeat.registry_file: /usr/share/filebeat/data/registry
setup.template.name: "filebeat-"
setup.template.pattern: "filebeat-*"
setup.dashboards.enabled: true

filebeat.modules:
- module: system
  syslog:
    var.paths: ["/var/log/host/system.log*"]
filebeat.inputs:
- type: docker
  containers.ids:
    path: "/var/lib/docker/containers"
    stream: "stdout"
    ids:
      - "*"
      enabled: true
  processors:
    - add_docker_metadata: ~

output.logstash:
    hosts: ['localhost:5000', 'localhost:5001']
    tls:
        insecure: true
output.elasticsearch:
  hosts: ["elasticsearch:9200"]