version: "3"
 
services:
  miservicio_mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=nombre
      - MYSQL_ROOT_PASSWORD=claveroot
      - MYSQL_USER=miusuario
      - MYSQL_PASSWORD=mipassword
    volumes:
      - ./volumenes/mysql:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 3306:3306
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:5000"
        syslog-format: "rfc3164"
        tag: "node-bd"
   
  miservicio_php:
    image: php:7-apache
    volumes:
      - ./miweb/:/var/www/html
    expose:
      - 80
    ports:
      - 80:80
    links: 
      - miservicio_mysql
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:5000"
        syslog-format: "rfc3164"
        tag: "node-apachePhp"
