packetbeat.interfaces.device: any
setup.template.name: "packetbeat-"
setup.template.pattern: "packetbeat-*"
setup.dashboards.enabled: true
setup.kibana.host: '127.0.0.1:5601'
setup.kibana.protocol: "http"
setup.kibana.path: ''

packetbeat.protocols:
- type: dns
  enabled: true
  ports: [53]
  include_authorities: true
  include_additionals: true
- type: http
  ports: [80, 8000, 8080, 9200, 32769, 5601]
packetbeat.flows:
  enabled: true
  timeout: 30s
  period: 10s

output.logstash:
  enabled: true
  hosts: ['127.0.0.1:5000']
  tls:
    insecure: true