packetbeat.interfaces.device: any
packetbeat.interfaces.type: af_packet
packetbeat.interfaces.buffer_size_mb: 100
setup.template.name: "packetbeat-"
setup.template.pattern: "packetbeat-*"

packetbeat.protocols:
- type: icmp
    enabled: true
    ports: [1,3,6,10,80]
- type: dhcpv4
    ports: [67, 68]
- type: dns
    enabled: true
    ports: [53]
    include_authorities: true
    include_additionals: true
- type: http
    enabled: true
    ports: [80, 5601, 8000, 8080, 9200, 32769]
    send_headers: ["User-Agent", "Cookie", "Set-Cookie"]
    send_response: true
    include_body_for: ["text/html"]

packetbeat.flows:
  enabled: true
  timeout: 30s
  period: 10s

output.logstash:
  enabled: true
  hosts: ['127.0.0.1:5000']
  tls:
    insecure: true