version: '2'

services:

  elasticsearch:
    environment:
      ELK_VERSION: 7.0.0
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $$ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk
    entrypoint: ["sh"]

  logstash:
    environment:
      ELK_VERSION: 7.0.0
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    build:
      context: logstash/
      args:
        ELK_VERSION: $$ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    networks:
      - elk
    depends_on:
      - elasticsearch
    entrypoint: ["sh"]

  kibana:
    environment:
      ELK_VERSION: 7.0.0
    build:
      context: kibana/
      args:
        ELK_VERSION: $$ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    entrypoint: ["sh"]

networks:

  elk:
    driver: bridge