version: '2'

services:

  elasticsearch:
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $$ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  logstash:
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    build:
      context: logstash/
      args:
        ELK_VERSION: $$ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "5001:5001"
      - "9600:9600"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $$ELK_VERSION
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat:
    build:
      context: filebeat/
      args:
        ELK_VERSION: $$ELK_VERSION
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/config/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - elk
    depends_on:
      - elasticsearch
      - logstash

  packetbeat:
    user: root
    build:
      context: packetbeat/
      args:
        ELK_VERSION: $$ELK_VERSION
    volumes:
      - ./packetbeat/config/packetbeat.yml:/usr/share/packetbeat/config/packetbeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    cap_add:
      - NET_RAW
      - NET_ADMIN
    command: ["--strict.perms=false"]
    networks:
      - elk
    depends_on:
      - elasticsearch
      - logstash

networks:
  elk:
    driver: bridge