setup.template.name: "filebeat-"
setup.template.pattern: "filebeat-*"
setup.dashboards.enabled: true
setup.kibana.host: 'kibana:5601'
setup.kibana.protocol: "http"
setup.kibana.path: ''
packetbeat.interfaces.device: any

packetbeat.protocols:
- type: dns
  ports: [53]
  include_authorities: true
  include_additionals: true
- type: http
  ports: [80, 8000, 8080, 9200]
packetbeat.flows:
  timeout: 30s
  period: 10s

output.logstash:
  hosts: ['logstash:5000']
  tls:
    insecure: true